### ISSUE TITLE
META-INF/gradle-plugins/org.openstreetmap.josm.properties in plugin jar?

### ISSUE THREAD

**Issue by Gubaer** [floscher/gradle-josm-plugin#10]
When I build the plugin and publish to my own maven directory hosted on S3,  the plugin jar includes the file
```
META-INF/gradle-plugins/org.openstreetmap.josm.properties
```
instead of the file
```
META-INF/gradle-plugins/gradle-josm-plugin.properties
```

When I want to load the plugin from my S3-based maven repo, I therefore have to 

1.  use the plugin id `org.openstreetmap.josm` instead of `gradle-josm-plugin`, see [build.gradle](https://github.com/Gubaer/josm-contourmerge-plugin/blob/master/build.gradle)

2.  add a resultion strategy to `settings.gradle`, see [settings.gradle](https://github.com/Gubaer/josm-contourmerge-plugin/blob/master/settings.gradle)

**Comment by floscher** [comment]
@Gubaer I'm currently on my phone, so can't test. Have you tried adding the version number in your `build.gradle`?:
```
plugins {
  id "org.openstreetmap.josm" version "1.2.3"
}
```
<del>Unfortunately you'd then have to hardcode the version number right there. That's a Gradle limitation for plugins that are not hosted in the Gradle plugin repository, these have to specify a hardcoded version number and if they don't want to, they would have to add a resolution strategy like you did.</del> You can now specify a plugin version number in the `build.gradle` file using a variable, see Gubaer/josm-contourmerge-plugin/pull/22

Don't know if that's it, will follow up, when I'm at my computer again.
