### ISSUE TITLE
How/where to add JVM Arguments to config?

### ISSUE THREAD

**Issue by ypcyc** [floscher/gradle-josm-plugin#19]
Recent JOSM versions start showing this warning at startup. I was trying to add those arguments, but I couldn't find how and where.
Can you help? @
![jvm_args](https://github.com/floscher/gradle-josm-plugin/assets/1402005/82228ae7-2639-490e-8d23-0393de02842b)

**Comment by floscher** [comment]
You mean when running the `runJosm` task? It extends [`JavaExec`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:jvmArgs(java.lang.Object[])), so it can be modified the same way:
```kotlin
tasks.runJosm {
  jvmArgs("arg1", "arg2", …)
}
```

**Comment by ypcyc** [comment]
Thank you!
I added this for debug to my build.gradle.kts:
```
tasks.debugJosm {
  jvmArgs(
    "--add-exports=java.base/sun.security.action=ALL-UNNAMED",
    "--add-exports=java.desktop/com.sun.imageio.plugins.jpeg=ALL-UNNAMED",
    "--add-exports=java.desktop/com.sun.imageio.spi=ALL-UNNAMED"
  )
}
```
