### ISSUE TITLE
build.gradle.kts - import of java-classes fails in IntelliJ- Any hint?

### ISSUE THREAD

**Issue by Gubaer** [floscher/gradle-josm-plugin#3]
Hi

when I import  the `gradle-josm-plugin` in IntelliJ, imports for java classes like `java.time.Duration` in `build.gradle.kts` don't work. In kotlin files they don't work either.

I googled but I didn't come up with a solution.

Do you use IntelliJ too? Did you have the same problem? Do you have a workaround? 

Thanks in advance!

**Comment by floscher** [comment]
Yes, I also use IntelliJ idea. But I didn't encounter this issue before.

If it is only classes from the JDK, it is probably the issue that IntelliJ can't find the JDK.
Does it only affect Kotlin files or also Java files?
Make sure that under `File › Project Structure… › Project Settings › Project` the project SDK is set correctly.
Under `File › Project Structure… › Platform Settings › SDKs` you can inspect the details of the available SDK choices or add a new one.

Does that already help?

**Comment by Gubaer** [comment]
Thanks!

I had to manually add the `$JAVA_HOME/jre/lib/rt.jar` to the SDKs classpath.  Seems to be fixed now.
